# Generated by Django 4.1.5 on 2023-06-17 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Katagori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Katagori Adı')),
            ],
        ),
        migrations.CreateModel(
            name='Tur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tür Adı')),
            ],
        ),
        migrations.AddField(
            model_name='movies',
            name='katagori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.katagori'),
        ),
        migrations.AddField(
            model_name='movies',
            name='tur',
            field=models.ManyToManyField(null=True, to='movies.tur'),
        ),
    ]
